### ISSUE TITLE
Question: missing 'implements' keyword

### ISSUE THREAD

**Issue by impankratov** [jelbourn/mix17-cdk-demo#1]
Hi, thanks for the awesome presentation!

I've noticed one thing in the demo: when you've added `ngAfterViewInit` method here:
https://github.com/jelbourn/mix17-cdk-demo/blob/226a994dcf4c604e4e7c7c232db4b77c6beb4a58/src/app/color-picker/color-picker.component.ts#L47
you haven't added the `implements AfterViewInit` to the ColorPicker component's class. However, the demo still worked (at least at the conference). 

Am I missed some new feature and we don't need to use `implements` for lifecycle hooks?

**Comment by detroitpistons16** [comment]
@impankratov I assume you figured it out by now, but in case you didn't or in case other people end up here, here is a short explanation regarding why it works without the 'implements x' part. From what I understand it has to do with the fact that there are no Interfaces in JS, so once the TS code gets transpiled, the implements part isn't in the code anymore. Angular was made to look after the method, and not not the interface.

**Comment by impankratov** [comment]
@detroitpistons16 thanks, that makes sense, haven't thought about it!
